#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import csv, json, hashlib, itertools, math, time
from pathlib import Path

ROOT = Path(r"C:\machura_ramsey_shadow_grid_1_10")
GRID = ROOT / "01_CASE_GRID" / "MACHURA_RAMSEY_CASE_GRID_1_10.csv"
RUNS = ROOT / "02_RUNS"
REPORTS = ROOT / "03_REPORTS"
FIGS = ROOT / "04_FIGURES"
EVID = ROOT / "05_EVIDENCE_SHA256"

MAX_N = 12
MAX_CLASSES_PER_LAYER = 200000
MAX_EXTENSIONS_PER_CASE = 5000000

def sha256_file(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1024*1024), b""):
            h.update(b)
    return h.hexdigest()

def pairs(n):
    return [(i,j) for i in range(n) for j in range(i+1,n)]

def bits_to_adj(n,bits):
    adj = [[0]*n for _ in range(n)]
    ps = pairs(n)
    for k,(i,j) in enumerate(ps):
        v = (bits >> k) & 1
        adj[i][j]=adj[j][i]=v
    return adj

def adj_to_bits(adj):
    n=len(adj); b=0; k=0
    for i in range(n):
        for j in range(i+1,n):
            if adj[i][j]: b |= (1<<k)
            k+=1
    return b

def permute_bits(n,bits,perm):
    adj=bits_to_adj(n,bits)
    out=[[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            out[i][j]=adj[perm[i]][perm[j]]
    return adj_to_bits(out)

def canon(n,bits):
    if n <= 8:
        best=None
        for p in itertools.permutations(range(n)):
            v=permute_bits(n,bits,p)
            if best is None or v < best:
                best=v
        return best
    return bits

def has_clique(adj, verts, red=True):
    for i in range(len(verts)):
        for j in range(i+1,len(verts)):
            e=adj[verts[i]][verts[j]]
            if red and e==0: return False
            if (not red) and e==1: return False
    return True

def is_clean(n,bits,a,b):
    adj=bits_to_adj(n,bits)
    if a <= 1 or b <= 1:
        return False
    for comb in itertools.combinations(range(n), a):
        if has_clique(adj, comb, True): return False
    for comb in itertools.combinations(range(n), b):
        if has_clique(adj, comb, False): return False
    return True

def predecessor_terms(n,bits,a,b):
    adj=bits_to_adj(n,bits)
    red_terms=[]
    blue_terms=[]
    if a-1 <= 0 or b-1 <= 0:
        return red_terms, blue_terms
    for comb in itertools.combinations(range(n), a-1):
        if has_clique(adj, comb, True): red_terms.append(comb)
    for comb in itertools.combinations(range(n), b-1):
        if has_clique(adj, comb, False): blue_terms.append(comb)
    return red_terms, blue_terms

def phi(red_terms, blue_terms, x):
    r=0; bl=0
    for t in red_terms:
        ok=True
        for i in t:
            if ((x>>i)&1)==0:
                ok=False; break
        if ok: r+=1
    for t in blue_terms:
        ok=True
        for i in t:
            if ((x>>i)&1)==1:
                ok=False; break
        if ok: bl+=1
    return r+bl

def extend_bits(n,bits,x):
    out=bits
    k=n*(n-1)//2
    for i in range(n):
        if (x>>i)&1:
            out |= (1 << (k+i))
    return out

def svg_axis(case_id, layers, path):
    w=900; h=220
    max_count=max([r["classes"] for r in layers] + [1])
    xs=[]
    for idx,r in enumerate(layers):
        x=70 + idx*((w-120)/max(1,len(layers)-1))
        y=150 - 90*(math.log10(r["classes"]+1)/math.log10(max_count+1))
        xs.append((x,y,r))
    poly=" ".join(f"{x:.1f},{y:.1f}" for x,y,r in xs)
    circles="\n".join(
        f'<circle cx="{x:.1f}" cy="{y:.1f}" r="5"/><text x="{x-12:.1f}" y="180" font-size="11">n={r["n"]}</text><text x="{x-22:.1f}" y="{y-10:.1f}" font-size="10">{r["classes"]}</text>'
        for x,y,r in xs
    )
    html=f'''<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}">
<rect width="100%" height="100%" fill="white"/>
<text x="30" y="30" font-size="20" font-family="Consolas">Machura Shadow Axis - {case_id}</text>
<line x1="50" y1="155" x2="850" y2="155" stroke="black"/>
<line x1="50" y1="45" x2="50" y2="155" stroke="black"/>
<polyline points="{poly}" fill="none" stroke="black" stroke-width="2"/>
{circles}
<text x="30" y="205" font-size="12" font-family="Consolas">classes per clean layer generated by Phi_G(x)=0</text>
</svg>'''
    path.write_text(html, encoding="utf-8")

def run_case(a,b):
    case_id=f"R{a}_{b}"
    case_name=f"R({a},{b})"
    run_dir=RUNS/case_id
    run_dir.mkdir(parents=True, exist_ok=True)
    REPORTS.mkdir(parents=True, exist_ok=True)
    FIGS.mkdir(parents=True, exist_ok=True)

    start=time.time()
    layers=[]
    rows=[]
    status="RUNNING"
    boundary=None

    if a==1 or b==1:
        layers=[{"n":0,"classes":1,"delta_next":1},{"n":1,"classes":0,"delta_next":None}]
        status="BOUNDARY_FOUND_TRIVIAL"
        boundary=1
    else:
        current={0}  # C_1: one vertex, no edges
        n=1
        total_ext=0
        while n <= MAX_N:
            next_set=set()
            local_min=None
            phi_hist={}
            for bits in current:
                red_terms, blue_terms = predecessor_terms(n,bits,a,b)
                for x in range(1<<n):
                    ph=phi(red_terms, blue_terms, x)
                    phi_hist[ph]=phi_hist.get(ph,0)+1
                    if local_min is None or ph<local_min:
                        local_min=ph
                    total_ext += 1
                    if ph==0:
                        nb=extend_bits(n,bits,x)
                        if is_clean(n+1,nb,a,b):
                            next_set.add(canon(n+1,nb))
                    if total_ext > MAX_EXTENSIONS_PER_CASE:
                        status="STOP_EXTENSION_LIMIT"
                        break
                if status=="STOP_EXTENSION_LIMIT":
                    break

            layers.append({"n":n,"classes":len(current),"delta_next":local_min})
            rows.append({
                "case_name":case_name,
                "a":a,"b":b,"n":n,
                "clean_layer_classes":len(current),
                "delta_n_to_n_plus_1":local_min,
                "next_layer_classes":len(next_set),
                "phi_hist":json.dumps(phi_hist, sort_keys=True)
            })

            if status=="STOP_EXTENSION_LIMIT":
                break

            if len(current)>0 and len(next_set)==0 and local_min is not None and local_min>0:
                boundary=n+1
                status="BOUNDARY_FOUND"
                layers.append({"n":n+1,"classes":0,"delta_next":None})
                break

            if len(next_set)>MAX_CLASSES_PER_LAYER:
                status="STOP_CLASS_LIMIT"
                layers.append({"n":n+1,"classes":len(next_set),"delta_next":None})
                break

            current=next_set
            n+=1

        if status=="RUNNING":
            status="STOP_MAX_N"

    csv_path=run_dir/f"{case_id}_layers.csv"
    with open(csv_path,"w",newline="",encoding="utf-8") as f:
        w=csv.DictWriter(f,fieldnames=["case_name","a","b","n","clean_layer_classes","delta_n_to_n_plus_1","next_layer_classes","phi_hist"])
        w.writeheader(); w.writerows(rows)

    summary={
        "case_name":case_name,
        "case_id":case_id,
        "a":a,"b":b,
        "status":status,
        "boundary_R_ab":boundary,
        "layers":layers,
        "elapsed_sec":round(time.time()-start,6)
    }
    json_path=run_dir/f"{case_id}_summary.json"
    json_path.write_text(json.dumps(summary,indent=2),encoding="utf-8")

    txt_path=REPORTS/f"{case_id}_summary.txt"
    txt_path.write_text(
        f"MACHURA SHADOW CASE {case_name}\n"
        f"status: {status}\n"
        f"boundary_R_ab: {boundary}\n"
        f"elapsed_sec: {summary['elapsed_sec']}\n"
        f"method: clean layers generated by Phi_G(x)=0\n"
        f"csv: {csv_path}\n"
        f"json: {json_path}\n",
        encoding="utf-8"
    )

    svg_path=FIGS/f"{case_id}_axis.svg"
    svg_axis(case_id,layers,svg_path)
    return summary

def main():
    for p in [RUNS,REPORTS,FIGS,EVID]:
        p.mkdir(parents=True, exist_ok=True)

    cases=[]
    with open(GRID,"r",encoding="utf-8-sig",newline="") as f:
        for r in csv.DictReader(f):
            cases.append((int(r["a"]), int(r["b"])))

    allsum=[]
    for a,b in cases:
        print(f"RUN R({a},{b})")
        allsum.append(run_case(a,b))

    master=REPORTS/"MASTER_GRID_1_10_SUMMARY.json"
    master.write_text(json.dumps(allsum,indent=2),encoding="utf-8")

    master_csv=REPORTS/"MASTER_GRID_1_10_SUMMARY.csv"
    with open(master_csv,"w",newline="",encoding="utf-8") as f:
        w=csv.DictWriter(f,fieldnames=["case_name","case_id","a","b","status","boundary_R_ab","elapsed_sec"])
        w.writeheader()
        for s in allsum:
            w.writerow({k:s.get(k) for k in ["case_name","case_id","a","b","status","boundary_R_ab","elapsed_sec"]})

    stamp=time.strftime("%Y%m%d_%H%M%S")
    manifest=EVID/f"MANIFEST_SHA256_GRID_V01_{stamp}.txt"
    lines=[]
    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and ".git" not in p.parts and "MANIFEST_SHA256_GRID_V01_" not in p.name:
            lines.append(f"{sha256_file(p)}  {p.relative_to(ROOT)}")
    manifest.write_text("\n".join(lines)+"\n",encoding="utf-8")
    print("DONE")
    print("MASTER:", master_csv)
    print("MANIFEST:", manifest)

if __name__=="__main__":
    main()
